[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = [ "-m", "flask", "--app", "/src/main", "run", "--debug", "--no-reload",]
env = [ "PYTHONEXECUTABLE=/bin/python",]

[package]
name = "hanyilong/flask-starter-9c9"
version = "0.2.0"
description = "Flask Wasmer starter package"
readme = "README.md"
repository = "https://github.com/hanyilong/flask-starter-9c9"

[dependencies]
"wasmer/python" = "^3.12.6"

[fs]
"/src" = "./src"
"/cpython/lib/python3.12" = "./.env/lib/python3.9"
